'use client';

/* eslint-disable @typescript-eslint/no-explicit-any */

interface PrintPageClientProps {
  tournament: any;
}

export default function PrintPageClient({ tournament }: PrintPageClientProps) {
  return (
    <div className="p-8 bg-white text-black print:p-4">
      <div className="text-center mb-8">
        <h1 className="text-2xl font-bold">{tournament.name}</h1>
        <p className="text-gray-600">
          {tournament.location}{tournament.city ? `, ${tournament.city}` : ''}
          {tournament.state ? `, ${tournament.state}` : ''}
        </p>
        <p className="text-sm text-gray-500">
          {new Date(tournament.date).toLocaleDateString()}
          {tournament.endDate ? ` — ${new Date(tournament.endDate).toLocaleDateString()}` : ''}
        </p>
      </div>

      {tournament.categories.map((cat: any) => (
        <div key={cat.id} className="mb-8 break-inside-avoid">
          <h2 className="text-xl font-bold border-b-2 border-black pb-1 mb-4">{cat.name}</h2>

          {/* Groups */}
          {cat.groups.length > 0 && (
            <div className="mb-4">
              <h3 className="font-semibold mb-2">Groups</h3>
              <div className="grid grid-cols-2 gap-4">
                {cat.groups.map((g: any) => (
                  <div key={g.id} className="border rounded p-2">
                    <h4 className="font-medium text-sm mb-1">{g.name}</h4>
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="border-b">
                          <th className="text-left py-1">Team</th>
                          <th className="text-center">W</th>
                          <th className="text-center">L</th>
                          <th className="text-center">+/-</th>
                        </tr>
                      </thead>
                      <tbody>
                        {g.players.map((p: any) => (
                          <tr key={p.id}>
                            <td className="py-0.5">{p.name}</td>
                            <td className="text-center">{p.wins}</td>
                            <td className="text-center">{p.losses}</td>
                            <td className="text-center">{p.pointDiff}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Games */}
          {cat.games.length > 0 && (
            <div>
              <h3 className="font-semibold mb-2">Games</h3>
              <table className="w-full text-xs border-collapse">
                <thead>
                  <tr className="border-b-2">
                    <th className="text-left py-1">#</th>
                    <th className="text-left">Round</th>
                    <th className="text-center">Court</th>
                    <th className="text-left">Home</th>
                    <th className="text-center">Score</th>
                    <th className="text-right">Away</th>
                  </tr>
                </thead>
                <tbody>
                  {cat.games.map((g: any) => (
                    <tr key={g.id} className="border-b">
                      <td className="py-0.5">{g.matchNumber || '—'}</td>
                      <td>{g.roundName || g.groupName || '—'}</td>
                      <td className="text-center">{g.courtNumber}</td>
                      <td>{g.homeTeam}</td>
                      <td className="text-center font-mono">
                        {g.scoreHome !== null ? `${g.scoreHome}-${g.scoreAway}` : '—'}
                      </td>
                      <td className="text-right">{g.awayTeam}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      ))}

      <div className="text-center mt-8 text-xs text-gray-400 print:mt-4">
        <button onClick={() => window.print()}
          className="px-4 py-2 bg-blue-600 text-white rounded print:hidden mb-4">
          🖨️ Print
        </button>
        <p>Generated by OneFTV</p>
      </div>
    </div>
  );
}
